---
- name: Installer les paquets nécessaires
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes

- name: Démarrer et activer MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Créer la base de données
  mysql_db:
    name: test
    state: present
    login_user: root
